In [2]:
import numpy as np
import pandas as pd


In [3]:
input_value=np.array([[0,0],[0,1],[1,1],[1,0]])
input_value.shape
input_value

array([[0, 0],
       [0, 1],
       [1, 1],
       [1, 0]])

In [15]:
output=np.array([0,1,0,1])
output=output.reshape(4,1)
output.shape

(4, 1)

In [5]:
weights=np.array([[1.2],[1.2]])
weights

array([[1.2],
       [1.2]])

In [6]:
bias = 0.5

In [7]:
def sigmoid_func(x):
    return 1/(1+np.exp(-x))

In [8]:
def der(x):
    return sigmoid_func(x)*(1-sigmoid_func(x))

In [18]:
for epochs in range(15000):
    input_arr = input_value
    
    weighted_sum=np.dot(input_arr,weights)+bias
    first_output=sigmoid_func(weighted_sum)


In [19]:
error=first_output - output
print(error)

[[ 0.5]
 [-0.5]
 [ 0.5]
 [-0.5]]


In [30]:
total_error=np.square(error).mean()
print(total_error)

0.25


In [50]:
first_der=error
second_der=der(first_output)
derivative=first_der*second_der
print(second_der)

[[0.23500371]
 [0.23500371]
 [0.23500371]
 [0.23500371]]


In [49]:

print(derivative)

[[ 0.11750186]
 [-0.11750186]
 [ 0.11750186]
 [-0.11750186]]


In [46]:
t_input = input_value.T
print(t_input)

[[0 0 1 1]
 [0 1 1 0]]


In [35]:
final_derivative=np.dot(t_input,derivative)
print(final_derivative)


[[0.]
 [0.]]


In [36]:

print(weights)

[[2.49129768e-16]
 [2.49129768e-16]]


In [37]:
for i in derivative:
        bias=bias-(0.05*i)

In [40]:
print(bias)

[-3.32199546e-16]


In [41]:
# for epochs in range(15000):
#     input_arr = input_value
    
#     weighted_sum=np.dot(input_arr,weights)+bias
#     first_output=sigmoid_func(weighted_sum)

#     error=first_output - output
#     total_error=np.square(error).mean()
    
# #     print(total_error)
 
#     first_der=error
#     second_der=der(first_output)
#     derivative=first_der*second_der
    
#     t_input = input_value.T
#     final_derivative=np.dot(t_input,derivative)
    
#     weights=weights - (0.05 * final_derivative)
    
#     for i in derivative:
#         bias=bias-(0.05*i)
        
# print(weights)
# print(bias)


In [57]:
pred=np.array([1,0])

result=np.dot(pred,weights)+bias
res=sigmoid_func(result)

print(res)

[0.5]
